# Generated by Django 4.2.3 on 2023-08-04 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/avatar/default.png', null=True, upload_to='img/avatar/'),
        ),
    ]
