# Generated by Django 4.2.3 on 2023-07-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0002_alter_product_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='products',
            field=models.ManyToManyField(blank=True, to='grocery.product'),
        ),
    ]
