# Generated by Django 4.2.3 on 2023-07-31 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_alter_grocery_user_alter_market_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='user',
        ),
        migrations.RemoveField(
            model_name='market',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
